---
- name: Install KRB5 workstation
  yum: name=krb5-workstation state=present update_cache=yes 
  delegate_to: "{{ item }}"
  with_items: "{{ groups['all_hadoop_nodes'] }}"


- name: Set krb5.conf
  template: src=krb5.conf.j2 dest=/etc/krb5.conf backup=yes
  delegate_to: "{{ item }}"
  with_items: "{{ groups['all_hadoop_nodes'] }}"

- name: Install KRB5 server
  yum: name={{ item }} state=present update_cache=yes
  with_items:
    - rng-tools
    - krb5-libs
    - krb5-server

- name: start entropy
  service: name=rngd state=started enabled=yes

- name: Set kdc.conf
  template: src=kdc.conf.j2 dest=/var/kerberos/krb5kdc/kdc.conf backup=yes
  notify:
    - restart kdc

- stat:
    path: /var/kerberos/krb5kdc/principal
  register: db

- name: Create KDC database
  command: /usr/sbin/kdb5_util create -s -P {{ krb5_kdc_master_passwd }} creates=/var/kerberos/krb5kdc/principal
  when: db.stat.islnk is not defined
  notify:
    - restart kdc

- name: Set kadm5.acl
  template: src=kadm5.acl.j2 dest=/var/kerberos/krb5kdc/kadm5.acl backup=yes
  notify:
    - restart kdc

- name: Check admin user exist
  shell: "kadmin.local -q 'list_principals' | grep -w '{{ krb5_kdc_admin_user }}'"
  ignore_errors: True
  register: kdc_admin_user
  changed_when: False


- name: Create Cloudera Manager admin princ
  command: /usr/sbin/kadmin.local -q "addprinc -pw {{ krb5_kdc_admin_passwd }} {{ krb5_kdc_admin_user }}"
  notify:
    - restart kdc
  when: "not kdc_admin_user.stdout"
