---
- name: restart agents
  service: name=cloudera-scm-agent state=restarted enabled=yes
  tags:
    - cdh

- name: wait cloudera-scm-server
  wait_for:
    host={{hostvars[groups['scm_mgmt'][0]] ['inventory_hostname']}}
    port={{ scm_port }}
    delay=5
    state=started
    timeout=300
  tags:
    - cdh