---
- name: Check whether cluster exists
  uri:
    url: "{{ cm_api_url }}/clusters/{{ cdh_cluster_name }}"
    method: GET
    status_code: 200,404
    force_basic_auth: yes
    user: "{{ scm_default_user }}"
    password: "{{ scm_default_pass }}"
    return_content: yes
    validate_certs: no
  register: clusters_resp

- set_fact: cluster_exists={{ 'True' if clusters_resp.status == 200 else 'False' }}
- debug: msg="Cluster '{{ cdh_cluster_name }}' exists - {{ cluster_exists }}"

- name: Import cluster template
  uri:
    url: "{{ cm_api_url }}/cm/importClusterTemplate?addRepositories=true"
    method: POST
    body_format: json
    body: "{{ lookup('template', 'base.j2') }}"
    status_code: 200
    force_basic_auth: yes
    user: "{{ scm_default_user }}"
    password: "{{ scm_default_pass }}"
    return_content: yes
    validate_certs: no
  register: template_resp
  when: cluster_exists == False

- debug: var=template_resp
  when: cluster_exists == False

- set_fact: command_id="{{ template_resp.json.id }}"
  when: cluster_exists == False

- debug: msg="Import cluster template command ID - {{ command_id }}"
  when: cluster_exists == False

- debug: msg="Login to Cloudera Manager to monitor import progress - http://{{ hostvars[groups['scm_mgmt'][0]] ['inventory_hostname'] }}:{{ scm_port }}/cmf/commands/commands"
  when: cluster_exists == False
