---
swappiness: 0
limits_path: /etc/security/limits.conf

limits:
    - { domain: hadoop, limit_type: -, limit_item: nofile,  value: 32768      }
    - { domain: hadoop, limit_type: -, limit_item: nproc,   value: unlimited  }
    - { domain: hdfs,   limit_type: -, limit_item: nofile,  value: 32768      }
    - { domain: hbase,  limit_type: -, limit_item: nofile,  value: 32768      }
    - { domain: spark,  limit_type: -, limit_item: nofile,  value: 65535      }
    - { domain: spark,  limit_type: -, limit_item: nproc,   value: 32768      }

defrag_path: 
    enabled: /sys/kernel/mm/redhat_transparent_hugepage/enabled
    defrag: /sys/kernel/mm/transparent_hugepage/defrag

rc_local: /etc/rc.local