---
- name: Update Cloudera Manager SSL Level 1settings
  uri:
    url: "{{ cm_api_url }}/cm/config"
    method: PUT
    body_format: json
    body: "{{ lookup('template', 'level1.j2') }}"
    status_code: 200
    force_basic_auth: yes
    user: "{{ scm_default_user }}"
    password: "{{ scm_default_pass }}"
    return_content: yes
  register: scm_resp

- debug: var=scm_resp

- name: Enabling SCM Agent SSL 
  lineinfile: dest=/etc/cloudera-scm-agent/config.ini regexp=^use_tls line=use_tls=1
  delegate_to: "{{ item }}"
  with_items: "{{ groups['all_hadoop_nodes'] }}"
  notify:
    - restart agents
    - restart server
    - wait cloudera-scm-server

- set_fact: cm_api_url="https://{{ hostvars[groups['scm_mgmt'][0]] ['inventory_hostname'] }}:{{ scm_ssl_port }}/api/{{ cm_api_version }}"

- debug: var=cm_api_url