---
- name: Install rsync
  yum: name=rsync state=present
  delegate_to: "{{ item }}"
  with_items: "{{ groups['all_hadoop_nodes'] }}"

- name: Install openssl perl
  yum: name=openssl-perl state=present
  delegate_to: "{{ item }}"
  with_items: "{{ groups['all_hadoop_nodes'] }}"

- name: copy PEM file to all agents
  synchronize:
    src: "{{cdh_encryption_key_location}}/x509/{{hostvars[inventory_hostname]['ansible_fqdn'] }}.pem"
    dest: "{{cdh_encryption_key_location}}/x509/"
  delegate_to: "{{ item }}"
  with_items: "{{ groups['scm_servers'] }}"

- name: Update Certificate path in SCM Agents
  lineinfile: dest=/etc/cloudera-scm-agent/config.ini regexp=^#\sverify_cert_file line=verify_cert_file={{cdh_encryption_key_location}}/x509/{{hostvars[inventory_hostname]['ansible_fqdn'] }}.pem
  delegate_to: "{{ item }}"
  with_items: "{{ groups['all_hadoop_nodes'] }}"

- name: Update Certificate path in SCM Agents
  lineinfile: dest=/etc/cloudera-scm-agent/config.ini regexp=^#\sverify_cert_dir line=verify_cert_dir={{cdh_encryption_key_location}}/CAcerts/
  delegate_to: "{{ item }}"
  with_items: "{{ groups['all_hadoop_nodes'] }}"
  notify:
    - restart agents