---
- name: Update Cloudera Manager settings
  uri:
    url: "{{ cm_api_url }}/cm/config"
    method: PUT
    body_format: json
    body: "{{ lookup('template', 'settings.j2') }}"
    status_code: 200
    force_basic_auth: yes
    user: "{{ scm_default_user }}"
    password: "{{ scm_default_pass }}"
    return_content: yes
  register: scm_resp

- debug: var=scm_resp

- name: Import KDC admin credentials
  uri:
    url: "{{ cm_api_url }}/cm/commands/importAdminCredentials?username={{ krb5_kdc_admin_user }}&password={{ krb5_kdc_admin_passwd }}"
    method: POST
    status_code: 200
    force_basic_auth: yes
    user: "{{ scm_default_user }}"
    password: "{{ scm_default_pass }}"
    return_content: yes
  when: krb5_kdc_type != 'none'