---
- name: Create PKI directory
  file:
    path: "{{cdh_encryption_key_location}}"
    state: directory
    owner: cloudera-scm
    group: cloudera-scm
    mode: 0755
  delegate_to: "{{ item }}"
  with_items: "{{ groups['all_hadoop_nodes'] }}" 

- name: Create x509 directory
  file:
    path: "{{cdh_encryption_key_location}}/x509"
    state: directory
    owner: cloudera-scm
    group: cloudera-scm
    mode: 0755
  delegate_to: "{{ item }}"
  with_items: "{{ groups['all_hadoop_nodes'] }}" 


- name: Create jks directory
  file:
    path: "{{cdh_encryption_key_location}}/jks"
    state: directory
    owner: cloudera-scm
    group: cloudera-scm
    mode: 0755
  delegate_to: "{{ item }}"
  with_items: "{{ groups['all_hadoop_nodes'] }}" 

- name: Create CAcerts directory
  file:
    path: "{{cdh_encryption_key_location}}/CAcerts"
    state: directory
    owner: cloudera-scm
    group: cloudera-scm
    mode: 0755
  delegate_to: "{{ item }}"
  with_items: "{{ groups['all_hadoop_nodes'] }}" 